// Consejos mensuales de jardín y huerta para Argentina (hemisferio sur).
// Contenido generado y verificado agronómicamente (hemisferio sur) por un equipo de agentes.
// No repite el calendario de siembra de la sección Huerta.

export type Flor = { nombre: string; cientifico: string; nota: string }
export type SuggestedTask = { title: string; category: 'jardin' | 'huerta' | 'almacigo' | 'mantenimiento' }

export type MonthTips = {
  estacion: 'Verano' | 'Otoño' | 'Invierno' | 'Primavera'
  destacado: string
  jardin: string[]
  huerta: string[]
  almacigos: string[]
  poda: string[]
  plagas: string[]
  mantenimiento: string[]
  flores_destacadas: Flor[]
  suggested_tasks: SuggestedTask[]
}

export const MONTHS = [
  'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
  'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre',
]

export const BITACORA: Record<number, MonthTips> = {
  1: {
    estacion: 'Verano',
    destacado: 'En el mes más caluroso, todo se juega en sostener la humedad: mulch, riego profundo y sombra para las plantas jóvenes.',
    jardin: ['Regar en profundidad muy temprano o de noche; nunca al sol del mediodía para evitar el golpe térmico y las quemaduras', 'Reforzar el mulch a 5-7 cm en todos los canteros para bajar la temperatura del suelo y espaciar riegos', 'Continuar el deadheading de anuales (petunias, zinnias, tagetes) y salvias para no cortar la floración', 'Dar sombra media a helechos, hortensias y plantas en maceta recién trasplantadas con media sombra o reubicándolas', 'Dividir lirios (Iris) y agapantos que ya terminaron su ciclo, y refrescar el follaje amarillento de bulbosas de primavera', 'Levantar y guardar en lugar fresco los bulbos de tulipán y narciso que ya secaron el follaje, para replantar en otoño'],
    huerta: ['Cosechar tomates, pimientos, berenjenas, zapallitos y pepinos a medida que maduran para estimular nueva fructificación', 'Sostener el riego parejo para evitar la pudrición apical del tomate y el amargor en pepinos y lechugas', 'Sembrar directo escarola, achicoria, chaucha y una tanda de albahaca y perejil a media sombra', 'Cosechar aromáticas (orégano, tomillo, romero) en plena floración para secar, cortando a media mañana', 'Renovar mulch de paja al pie de las hortalizas de fruto para proteger raíces del calor extremo'],
    almacigos: ['Repollo, brócoli y coliflor de otoño (Brassica oleracea)', 'Apio (Apium graveolens) para trasplante otoñal', 'Prímula (Primula malacoides) para florecer en invierno', 'Cineraria (Pericallis x hybrida) para color de fin de invierno'],
    poda: ['Época de poca poda: solo limpieza de ramas secas, quebradas o flores agotadas', 'Despuntar suavemente las anuales que se ahilan por el calor para que rebroten compactas', 'Evitar podas fuertes de arbustos y árboles: el sol directo quema la corteza y la madera expuesta'],
    plagas: ['Mosca blanca en tomates y aromáticas: colocar trampas cromáticas amarillas y pulverizar jabón potásico al envés', 'Cochinilla en cítricos, rosas y plantas de interior sacadas afuera: pincelar con alcohol o aplicar aceite mineral al atardecer', 'Hongos por riego nocturno excesivo (oidio, botritis): regar al suelo y no al follaje, y ventilar las plantas apiñadas'],
    mantenimiento: ['Chequear a diario el riego por goteo por obstrucciones; el calor evapora rápido y las plantas en maceta pueden secarse en horas', 'Mantener la compostera húmeda como esponja escurrida y a la sombra para que no se detenga por sequedad', 'Limpiar y agrupar las macetas en zonas de media sombra para las vacaciones, con hidrogel o botellas de riego lento'],
    flores_destacadas: [{ nombre: 'Hortensia', cientifico: 'Hydrangea macrophylla', nota: 'En su pico de floración a media sombra; el color de sus pompones (azul o rosa) depende del pH del suelo, un lujo de patios y galerías.' }, { nombre: 'Rosa china / Hibisco', cientifico: 'Hibiscus rosa-sinensis', nota: 'Flores enormes y tropicales que se renuevan a diario en pleno calor; imprescindible para dar aire subtropical al jardín.' }, { nombre: 'Zinnia', cientifico: 'Zinnia elegans', nota: 'La anual del verano por excelencia: resiste calor y sequía, florece en todos los colores y es ideal para flor de corte.' }],
    suggested_tasks: [{ title: 'Reforzar el mulch de los canteros', category: 'mantenimiento' }, { title: 'Regar en profundidad de noche', category: 'jardin' }, { title: 'Cosechar tomates y zapallitos', category: 'huerta' }, { title: 'Colocar trampas amarillas contra mosca blanca', category: 'mantenimiento' }, { title: 'Sembrar almácigo de brócoli de otoño', category: 'almacigo' }],
  },
  2: {
    estacion: 'Verano',
    destacado: 'Con las noches empezando a refrescar, es el mes bisagra: se planifica el otoño mientras el jardín aún da su última gran floración.',
    jardin: ['Mantener el riego profundo, pero empezar a espaciarlo a medida que bajan las temperaturas nocturnas', 'Hacer una última fertilización liviana de anuales y rosas; luego frenar para que las plantas se preparen para el otoño', 'Dividir y trasplantar perennes de floración primaveral y estival (agapanto, hemerocallis, salvias, sedum)', 'Recortar y renovar canteros de anuales agotadas y planificar el reemplazo con especies de otoño', 'Preparar y airear la tierra de los canteros donde irán los bulbos de primavera el mes próximo', 'Seguir con el deadheading de rosas para asegurar una buena floración de fin de verano y otoño'],
    huerta: ['Cosechar el grueso de tomates, pimientos, berenjenas y zapallos, y guardar semillas de las mejores plantas', 'Iniciar la siembra directa de cultivos de otoño-invierno: acelga, espinaca, rúcula, rabanito y nabo', 'Sacar plantas de verano ya agotadas y sembrar abono verde (avena, mostaza) en los canteros que quedan libres', 'Sembrar directo arveja y habas hacia fin de mes en zonas más frescas', 'Cosechar y secar las últimas aromáticas antes de que pierdan aceites esenciales con el fin del verano'],
    almacigos: ['Acelga y espinaca (Beta vulgaris / Spinacia oleracea)', 'Lechuga de otoño (Lactuca sativa)', 'Alelí (Matthiola incana) para flor de corte de otoño-invierno', 'Conejito / boca de dragón (Antirrhinum majus) para color de fin de invierno', 'Caléndula (Calendula officinalis) para floración otoño-invierno'],
    poda: ['Poda de verano en cítricos: aclarar ramas interiores para ventilar y entrar luz, sin exceso', 'Recortar aromáticas y lavandas tras la floración para mantenerlas compactas antes del otoño', 'Despuntar setos y arbustos de crecimiento rápido en su último empuje de la temporada cálida'],
    plagas: ['Hongos de fin de verano (tizón, oidio) favorecidos por el rocío nocturno: retirar hojas afectadas y aplicar caldo bordelés', 'Isocas y orugas defoliadoras en huerta y ornamentales: control con Bacillus thuringiensis o recolección manual al atardecer', 'Cochinilla y pulgones que rebrotan con el follaje nuevo de otoño: monitorear y tratar con jabón potásico y aceite mineral'],
    mantenimiento: ['Empezar a incorporar los restos de plantas de verano a la compostera para tener abono maduro en primavera', 'Revisar tutores, estacas y espalderas antes de las lluvias y vientos de otoño; reforzar lo que esté flojo', 'Hacer mantenimiento a fondo de herramientas de corte: afilar, limpiar y aceitar antes de la temporada de poda otoñal'],
    flores_destacadas: [{ nombre: 'Dalia', cientifico: 'Dahlia pinnata', nota: 'En su esplendor de fin de verano con flores exuberantes en todo el espectro de colores; excelente para corte y para dar volumen al cantero.' }, { nombre: 'Cosmos', cientifico: 'Cosmos bipinnatus', nota: 'Anual liviana y aireada que florece incansable hasta el otoño; se resiembra sola y atrae abejas y mariposas al jardín.' }, { nombre: 'Crespón / Árbol de Júpiter', cientifico: 'Lagerstroemia indica', nota: 'El árbol estrella del verano tardío: panojas crespas en fucsia, rosa o blanco que aguantan el calor y prolongan el color en la vereda.' }],
    suggested_tasks: [{ title: 'Dividir matas de agapanto y hemerocallis', category: 'jardin' }, { title: 'Sembrar acelga y espinaca para otoño', category: 'huerta' }, { title: 'Guardar semillas de tomate', category: 'huerta' }, { title: 'Sembrar almácigo de caléndula', category: 'almacigo' }, { title: 'Afilar y aceitar herramientas de poda', category: 'mantenimiento' }],
  },
  3: {
    estacion: 'Otoño',
    destacado: 'Marzo abre el otoño con calor que afloja: es el mes para dividir matas, planificar los bulbos de primavera y arrancar los almácigos de otoño-invierno.',
    jardin: ['Reducí gradualmente la frecuencia de riego a medida que bajan las temperaturas y aumenta la humedad ambiente, pero sostené el aporte en días de calor seco.', 'Dividí matas de herbáceas perennes que se agrandaron en verano: agapantos, hemerocallis, sedum y gramíneas ornamentales rebrotan mejor si las separás ahora.', 'Aplicá una última fertilización liviana a rosales y arbustos de flor con un balanceado de baja concentración; evitá excesos de nitrógeno que estimulen brotes tiernos frente al frío.', 'Sacá flores marchitas (deadheading) de dalias, cosmos, zinnias y salvias para prolongar la floración de fin de temporada.', 'Empezá a airear y descompactar el suelo de los canteros incorporando compost maduro antes de las lluvias otoñales.', 'Refrescá el césped con una resiembra ligera en zonas ralas: es buen momento para gramíneas de estación fría (raigrás, festuca).'],
    huerta: ['Cosechá lo que queda del verano: tomates, pimientos, berenjenas, zapallitos y albahaca antes de las primeras noches frescas.', 'Sembrá directamente hortalizas de hoja y raíz para otoño: acelga, espinaca, rúcula, rabanito, zanahoria y remolacha.', 'Plantá plantines de brásicas (repollo, brócoli, coliflor) si no los hiciste en almácigo el mes anterior.', 'Incorporá abono verde o compost en los canteros que quedaron libres tras la cosecha de verano.', 'Sembrá arvejas y habas de forma escalonada para asegurar cosechas de invierno.'],
    almacigos: ['Repollo, brócoli y coliflor (Brassica oleracea) para trasplantar en abril-mayo.', 'Lechuga de invierno (Lactuca sativa), variedades resistentes al frío como mantecosa y criolla.', 'Cebolla de día corto (Allium cepa) para plantines de fin de otoño.', 'Pensamiento y viola (Viola x wittrockiana) para floración otoño-invierno.'],
    poda: ['Podá suavemente rosales reflorecientes retirando ramas agotadas y flores pasadas; reservá la poda fuerte de formación para el invierno (julio).', 'Despuntá arbustos de verano que terminaron de florecer para ordenar la mata, sin cortes drásticos.', 'Recortá gramíneas ornamentales solo si están muy desprolijas; conviene dejarlas para el interés invernal.'],
    plagas: ['Oídio en zapallos, rosales y crucíferas por la amplitud térmica: ventilá, evitá mojar el follaje y aplicá azufre o leche diluida al 10%.', 'Pulgones en brotes tiernos de brásicas y ornamentales: controlá con jabón potásico o liberando vaquitas de San Antonio (Coccinellidae).', 'Caracoles y babosas activados por las lluvias otoñales: usá trampas de cerveza, barreras de ceniza o cáscara de huevo alrededor de plantines.'],
    mantenimiento: ['Limpiá, afilá y desinfectá tijeras y herramientas de poda con alcohol antes de la temporada de cortes de otoño-invierno.', 'Empezá una compostera de otoño equilibrando restos verdes de cosecha con material seco (hojas, paja).', 'Revisá y guardá el sistema de riego por goteo del verano; reducí los tiempos programados según la nueva demanda.'],
    flores_destacadas: [{ nombre: 'Dalia', cientifico: 'Dahlia pinnata', nota: 'En pleno esplendor de fin de verano: colores intensos del rojo al naranja; cosechá flores para florero y marcá las matas para desenterrar tubérculos en invierno.' }, { nombre: 'Cosmos', cientifico: 'Cosmos bipinnatus', nota: 'Floración generosa en rosa, blanco y fucsia que atrae polinizadores; ideal para bordes silvestres y macizos de bajo mantenimiento.' }, { nombre: 'Anémona de otoño', cientifico: 'Anemone hupehensis', nota: 'Aporta elegancia a la media sombra con flores blancas o rosadas sobre tallos altos; perfecta para iluminar rincones frescos del jardín.' }],
    suggested_tasks: [{ title: 'Dividir matas de agapanto y hemerocallis', category: 'jardin' }, { title: 'Sembrar acelga y espinaca directo', category: 'huerta' }, { title: 'Armar almácigo de brócoli y repollo', category: 'almacigo' }, { title: 'Afilar y desinfectar tijeras de poda', category: 'mantenimiento' }, { title: 'Incorporar compost a canteros libres', category: 'mantenimiento' }],
  },
  4: {
    estacion: 'Otoño',
    destacado: 'Abril es el corazón del otoño: llegó el momento de plantar los bulbos de primavera y de aprovechar el suelo tibio y húmedo para trasplantar árboles y arbustos.',
    jardin: ['Plantá bulbos de primavera ahora que el suelo se enfría: tulipanes, narcisos, jacintos, muscari y anémonas van a tierra durante el otoño.', 'Trasplantá árboles, arbustos y rosales a raíz desnuda o en pan de tierra; el suelo tibio y las lluvias favorecen el enraizado antes del invierno.', 'Reducí el riego general: la evapotranspiración cae y el exceso de agua favorece hongos radiculares.', 'Recogé y compostá las hojas caídas, o usalas como mulch sobre los canteros para proteger raíces del frío.', 'Plantá herbáceas de otoño-invierno para color: pensamientos, violas, primulas y alelíes en macizos y macetas.', 'Fertilizá el césped con un abono otoñal rico en potasio y fósforo para fortalecer raíces antes del frío.'],
    huerta: ['Trasplantá al cantero definitivo los plantines de brásicas, lechugas y cebollas hechos en almácigo.', 'Sembrá directo habas, arvejas, ajo y hortalizas de hoja resistentes al frío (acelga, espinaca, radicheta).', 'Plantá los dientes de ajo (Allium sativum) con la punta hacia arriba: abril es el mes clásico para el ajo en la región pampeana.', 'Tutorá y protegé las arvejas en crecimiento con ramas o alambre.', 'Cubrí el suelo con mulch entre las hileras para conservar humedad y frenar malezas.'],
    almacigos: ['Habas (Vicia faba) y arvejas (Pisum sativum) —aunque van bien directas, podés adelantarlas en cepellón.', 'Cebolla de día corto (Allium cepa) para plantines de invierno.', 'Espuela de caballero / consólida (Consolida ajacis) para floración de primavera.', 'Caléndula (Calendula officinalis) para color de invierno-primavera.'],
    poda: ['Podá arbustos de floración estival ya terminados (hibisco, buddleja) para dar forma antes del reposo.', 'Retirá ramas secas, enfermas o cruzadas de árboles caducos a medida que pierden la hoja y se ve mejor la estructura.', 'Evitá podar arbustos de floración primaveral (jazmín, forsitia, azalea): ya tienen los pimpollos formados y perderías la flor.'],
    plagas: ['Hongos de suelo (Pythium, Rhizoctonia) por el exceso de humedad: mejorá el drenaje y no riegues de más en trasplantes.', 'Roya y manchas foliares en el follaje que se moja y no seca: retirá hojas afectadas y mejorá la ventilación.', 'Babosas y caracoles sobre plantines tiernos recién trasplantados: mantené trampas y barreras activas tras cada lluvia.'],
    mantenimiento: ['Juntá hojas caídas para armar mantillo (leaf mould) o incorporarlas a la compostera como material marrón.', 'Renová la capa de mulch orgánico en canteros y al pie de arbustos para aislar el suelo del frío.', 'Revisá tutores, estacas y ataduras antes de los vientos y lluvias otoñales; ajustá lo que esté flojo.'],
    flores_destacadas: [{ nombre: 'Crisantemo', cientifico: 'Chrysanthemum morifolium', nota: 'La flor emblema del otoño: floración abundante en toda la gama cálida, ideal para macizos, macetas y flor de corte que dura mucho en agua.' }, { nombre: 'Aster de otoño', cientifico: 'Symphyotrichum novi-belgii', nota: 'Nubes de flores lila, violeta y rosa que sostienen a los polinizadores al final de la temporada; excelente para bordes naturalistas.' }, { nombre: 'Ciclamen', cientifico: 'Cyclamen persicum', nota: 'Perfecto para plantar ahora en media sombra y macetas; florece en otoño-invierno con tonos del blanco al fucsia y follaje jaspeado decorativo.' }],
    suggested_tasks: [{ title: 'Plantar bulbos de tulipán y narciso', category: 'jardin' }, { title: 'Plantar dientes de ajo en la huerta', category: 'huerta' }, { title: 'Trasplantar plantines de lechuga y repollo', category: 'huerta' }, { title: 'Sembrar caléndula en almácigo', category: 'almacigo' }, { title: 'Juntar hojas y renovar el mulch', category: 'mantenimiento' }],
  },
  5: {
    estacion: 'Otoño',
    destacado: 'Mayo cierra el otoño preparando el jardín para el frío: última ventana para bulbos, protección de especies sensibles y a punto de arrancar la gran poda invernal.',
    jardin: ['Aprovechá los últimos días para terminar de plantar bulbos de primavera; los tulipanes agradecen incluso el frío de mayo antes de brotar.', 'Protegé plantas sensibles a la helada (cala, dalia, plantas tropicales en maceta) con mulch grueso, mantas o llevándolas a resguardo.', 'Suspendé la fertilización de la mayoría de las especies: el jardín entra en reposo y no debe estimularse el crecimiento.', 'Regá solo lo indispensable, preferentemente en la mañana para que el follaje seque y evitar daño por escarcha.', 'Desenterrá y guardá tubérculos de dalia y gladiolos si tu zona tiene heladas fuertes; secalos y almacenalos en lugar fresco y seco.', 'Terminá de plantar árboles y arbustos caducos a raíz desnuda mientras dure el reposo vegetativo.'],
    huerta: ['Cosechá hortalizas de hoja de otoño (acelga, espinaca, lechuga) y las primeras raíces (rabanito, nabo).', 'Sembrá directo habas, arvejas y ajo si todavía no lo hiciste; aún estás a tiempo en la región pampeana.', 'Protegé los cultivos de invierno con mulch o tela antihelada (agrotextil) ante los primeros fríos intensos.', 'Realizá un abonado de fondo con compost o estiércol maduro en canteros que descansarán, para que se integre durante el invierno.', 'Plantá plantines de cebolla y de crucíferas para cosechas de invierno-primavera.'],
    almacigos: ['Habas (Vicia faba) y arvejas (Pisum sativum) en siembra tardía protegida.', 'Cebolla de día corto (Allium cepa) para últimos plantines de la temporada.', 'Alhelí (Matthiola incana) para floración perfumada de primavera.', 'Nomeolvides (Myosotis sylvatica) para tapices florales de primavera temprana.'],
    poda: ['Comenzá a limpiar árboles y arbustos caducos ya sin hojas, retirando ramas muertas y mal orientadas.', 'Podá frutales de pepita (manzano, peral) en pleno reposo; en los de carozo (ciruelo, duraznero) elegí días secos o dejá la poda para fin de invierno, ya que el corte en humedad favorece enfermedades de la madera.', 'Reservá la poda fuerte de rosales para pleno invierno (junio-julio); en mayo solo despuntá para reducir el vareo por viento.'],
    plagas: ['Cochinillas resguardadas en tallos y ejes de arbustos: aplicá aceite mineral hortícola aprovechando el reposo vegetativo.', 'Hongos de reposo (roya, manchas) sobre hojarasca: recogé y descartá restos enfermos para reducir el inóculo del año próximo.', 'Babosas y caracoles que buscan refugio: seguí con trampas y despejá escondrijos húmedos cerca de los plantines.'],
    mantenimiento: ['Hacé una limpieza general de canteros retirando restos de cultivos de verano ya agotados y malezas.', 'Volteá y cubrí la compostera para conservar calor y actividad durante el invierno.', 'Limpiá, secá y guardá mangueras, aspersores y programadores del sistema de riego que no se usarán en invierno.'],
    flores_destacadas: [{ nombre: 'Camelia', cientifico: 'Camellia japonica', nota: 'Empieza a mostrar sus primeros pimpollos para el invierno; arbusto de media sombra con flores impecables blancas, rosas o rojas y follaje lustroso todo el año.' }, { nombre: 'Caléndula', cientifico: 'Calendula officinalis', nota: 'Rústica y luminosa, aporta naranja y amarillo al jardín frío; comestible, medicinal y aliada de la huerta como planta trampa de pulgones.' }, { nombre: 'Alhelí de invierno', cientifico: 'Erysimum cheiri', nota: 'Ideal para plantar ahora en macizos y bordes; sus flores perfumadas en tonos cálidos acompañan desde el fin del otoño hasta la primavera.' }],
    suggested_tasks: [{ title: 'Desenterrar y guardar tubérculos de dalia', category: 'jardin' }, { title: 'Proteger plantas sensibles con mulch', category: 'jardin' }, { title: 'Sembrar habas y arvejas directo', category: 'huerta' }, { title: 'Sembrar alhelí en almácigo', category: 'almacigo' }, { title: 'Voltear y cubrir la compostera para el invierno', category: 'mantenimiento' }],
  },
  6: {
    estacion: 'Invierno',
    destacado: 'Junio es el mes de plantar a raíz desnuda: rosales, frutales y árboles caducos entran dormidos, y es tu mejor ventana del año para hacerlo.',
    jardin: ['Plantá rosales, frutales de pepita y árboles caducos a raíz desnuda mientras están en reposo: el suelo fresco favorece el enraizamiento sin estrés.', 'Reducí el riego al mínimo; con las lluvias y la baja evaporación, la mayoría de los canteros no necesita agua extra salvo perennes en macetas bajo alero.', 'Suspendé toda fertilización de ornamentales: las plantas están dormidas y el abono se lava o estimula brotes tiernos que la helada quema.', 'Protegé especies sensibles al frío (cala, papiro, plectranthus) con mulch grueso al pie o llevá las macetas contra una pared orientada al norte.', 'Dividí y trasplantá matas de herbáceas perennes en reposo: agapanto, hemerocallis, cortadera y gramíneas se separan bien ahora.', 'Si te quedaron bulbos de floración primaveral sin plantar, aprovechá los días secos para colocarlos ya (el tulipán es el que mejor tolera la plantación tardía): es tu última ventana antes de que rompan dormancia.'],
    huerta: ['Cosechá hortalizas de hoja de estación fría: acelga, espinaca, lechuga de invierno, radicheta y rúcula, que están en su mejor punto.', 'Sembrá directamente habas, arvejas y ajo, cultivos que prosperan con el frío y toleran heladas suaves.', 'Cubrí con mulch o paja los canteros de zanahoria, remolacha y nabo para proteger las raíces y facilitar la cosecha escalonada.', 'Raleá y tutorá las habas ya emergidas para que resistan el viento y armá los surcos de las arvejas trepadoras.', 'Aireá el compost y sumá restos de poda picados; en invierno se descompone lento, así que mantené la pila húmeda y protegida.'],
    almacigos: ['Cebolla de día largo (Allium cepa) para trasplantar en primavera.', 'Puerro (Allium porrum) en cajón protegido del frío intenso.', 'Pensamiento y viola (Viola × wittrockiana) para floración de fin de invierno.', 'Alhelí (Matthiola incana) en almácigo protegido para color y perfume primaveral.'],
    poda: ['Podá árboles y arbustos caducos en pleno reposo (paraíso, ciruelo de jardín, hortensia paniculata): sin hojas ves bien la estructura y las heridas cicatrizan antes del brote.', 'Retrasá la poda del rosal a fin de julio o agosto; en junio limitate a sacar madera muerta o enferma.', 'No podes especies de floración primaveral como las que florecen sobre madera vieja (forsythia, weigela): perderías la floración.'],
    plagas: ['Cochinilla en cítricos y camelias: revisá el envés y ramas, y aplicá aceite mineral en día templado y seco para asfixiarlas.', 'Hongos de suelo y podredumbre por exceso de humedad: mejorá el drenaje y evitá regar de más en tierra ya fría.', 'Babosas y caracoles sobre plántulas de hoja: colocá trampas de cerveza o barreras de ceniza alrededor de los canteros tiernos.'],
    mantenimiento: ['Afilá, limpiá y desinfectá tijeras y serruchos de poda con alcohol entre planta y planta para no transmitir enfermedades.', 'Renová el mulch de canteros y pie de árboles a 5-7 cm para conservar temperatura y humedad del suelo.', 'Revisá y purgá el sistema de riego por goteo antes de que una helada fuerte reviente mangueras o goteros con agua adentro.'],
    flores_destacadas: [{ nombre: 'Camelia', cientifico: 'Camellia japonica', nota: 'Reina del invierno a media sombra: flores en blanco, rosa y rojo sobre follaje lustroso, ideal para el sector fresco y húmedo del jardín.' }, { nombre: 'Jazmín de invierno', cientifico: 'Jasminum nudiflorum', nota: 'Florece amarillo intenso sobre ramas desnudas antes de las hojas; perfecto para tapizar muros o taludes y alegrar el mes más gris.' }, { nombre: 'Caléndula', cientifico: 'Calendula officinalis', nota: 'Naranja y amarillo que no se apaga con el frío; rústica, comestible y auxiliar de la huerta por atraer benéficos.' }],
    suggested_tasks: [{ title: 'Plantar rosales a raíz desnuda', category: 'jardin' }, { title: 'Sembrar habas y arvejas', category: 'huerta' }, { title: 'Almácigo de cebolla', category: 'almacigo' }, { title: 'Desinfectar tijeras de poda', category: 'mantenimiento' }, { title: 'Renovar mulch en canteros', category: 'mantenimiento' }],
  },
  7: {
    estacion: 'Invierno',
    destacado: 'Julio es el corazón del reposo: mes de podas fuertes de frutales y rosales, con las plantas profundamente dormidas y el jardín en pausa.',
    jardin: ['Realizá la poda de formación y fructificación de rosales hacia fin de mes: rebajá a 3-5 yemas por rama y limpiá el centro para airear la mata.', 'Seguí plantando a raíz desnuda; julio todavía es buena ventana para árboles y arbustos caducos antes del despertar.', 'Mantené el riego suspendido o mínimo: el suelo frío retiene humedad y el exceso pudre raíces dormidas.', 'Protegé del frío las macetas de especies subtropicales agrupándolas y envolviendo los contenedores para que no se congele el pan de tierra.', 'Terminá la división de matas de perennes (agapanto, lirios, hemerocallis) mientras aún no hay brotación.', 'Limpiá canteros de hojas caídas y malezas de invierno para reducir refugio de plagas y hongos de cara a la primavera.'],
    huerta: ['Cosechá coles de estación fría (repollo, coliflor, brócoli), acelga y hojas verdes que están en pleno rinde.', 'Sembrá directamente más habas, arvejas y otra tanda de ajo para escalonar la cosecha.', 'Prepará los canteros de primavera: incorporá compost maduro y remové apenas para que el suelo se airee y madure.', 'Tutorá y aporcá las habas y arvejas ya crecidas para protegerlas del viento y las heladas.', 'Controlá el drenaje de la huerta tras lluvias prolongadas para evitar encharcamiento y asfixia radicular.'],
    almacigos: ['Tomate (Solanum lycopersicum) en almácigo protegido con calor de fondo, para adelantar la temporada.', 'Pimiento y ají (Capsicum annuum) en cajón cálido y luminoso, especies que necesitan largo ciclo.', 'Copete o tagetes (Tagetes patula) para tener plantines listos al arrancar la primavera.', 'Conejito o boca de dragón (Antirrhinum majus) en almácigo protegido para floración temprana.'],
    poda: ['Podá frutales de pepita y carozo en pleno reposo (manzano, peral, ciruelo, durazno): eliminá chupones, ramas cruzadas y abrí el centro de la copa.', 'Ejecutá la poda anual del rosal a fin de julio, el momento clásico antes de la brotación primaveral.', 'Podá hortensias macrophylla solo sacando flores secas y madera vieja, cuidando las yemas gordas que darán flor.'],
    plagas: ['Huevos y formas invernantes de plagas en corteza y ramas: aplicá caldo bordelés o aceite mineral como tratamiento de invierno preventivo en frutales.', 'Oídio y manchas foliares en rosales y perennes por humedad y poca ventilación: retirá hojas afectadas y mejorá la aireación con la poda.', 'Pulgón que empieza a aparecer en brotes tiernos de días templados: controlá con jabón potásico apenas los detectes.'],
    mantenimiento: ['Aprovechá el reposo para reparar, pintar y aceitar herramientas, tutores, canteros elevados y estructuras de madera.', 'Sellá los cortes grandes de poda de frutales con pasta cicatrizante para prevenir el ingreso de hongos.', 'Volteá y humedecé la pila de compost; sumá material seco para equilibrar y sostener la actividad pese al frío.'],
    flores_destacadas: [{ nombre: 'Aromo', cientifico: 'Acacia dealbata', nota: 'Estalla en pompones amarillos perfumados en pleno invierno; árbol de rápido crecimiento que anuncia el fin de la estación fría.' }, { nombre: 'Damasco de flor', cientifico: 'Prunus mume', nota: 'Uno de los primeros en abrir en pleno invierno: cubre sus ramas desnudas de flores blancas a rosadas y perfumadas, adelantándose a todos los frutales de flor.' }, { nombre: 'Primavera de jardín', cientifico: 'Primula malacoides', nota: 'Nubes de flores lila, rosa y blanca para dar color al invierno en canteros y macetas a media sombra.' }],
    suggested_tasks: [{ title: 'Podar rosales', category: 'jardin' }, { title: 'Podar frutales en reposo', category: 'jardin' }, { title: 'Almácigo de tomate y pimiento', category: 'almacigo' }, { title: 'Aplicar caldo bordelés en frutales', category: 'huerta' }, { title: 'Voltear el compost', category: 'mantenimiento' }],
  },
  8: {
    estacion: 'Invierno',
    destacado: 'Agosto despierta el jardín: mes clave de almácigos de primavera y verano bajo protección, con el suelo empezando a entibiarse.',
    jardin: ['Reactivá gradualmente el riego a medida que suben las temperaturas y las plantas insinúan los primeros brotes.', 'Aplicá una primera fertilización suave de arranque con compost o abono de liberación lenta al pie de perennes y arbustos que despiertan.', 'Terminá las últimas plantaciones a raíz desnuda y las divisiones de matas antes de que la brotación esté avanzada.', 'Limpiá y prepará canteros: sacá malezas, aflojá la tierra e incorporá materia orgánica para recibir la explosión primaveral.', 'Retirá progresivamente las protecciones de invierno de las macetas y especies sensibles en los días más templados, atento a heladas tardías.', 'Revisá los bulbos de primavera que ya asoman y despejá el mulch por encima para que emerjan sin obstáculo.'],
    huerta: ['Cosechá las últimas hojas de invierno, arvejas tempranas, coles y el ajo y la cebolla que ya se acercan a punto.', 'Sembrá directamente rúcula, rabanito, acelga, lechuga y una tanda de zanahoria aprovechando el suelo entibiándose.', 'Prepará y abona los canteros donde irán tomate, pimiento y berenjena, con buen aporte de compost maduro.', 'Endurecé (rustificá) los plantines de estación cálida sacándolos de a ratos al exterior antes del trasplante.', 'Tutorá arvejas y habas en pleno crecimiento y controlá el aporcado del ajo.'],
    almacigos: ['Tomate, pimiento y berenjena (Solanum spp. y Capsicum annuum): mes central para almácigo protegido de solanáceas.', 'Albahaca (Ocimum basilicum) en cajón cálido, ya que germina con temperatura de fondo.', 'Zinnia (Zinnia elegans) y cosmos (Cosmos bipinnatus) para tener plantines florales listos en primavera.', 'Petunia (Petunia × hybrida) en almácigo fino y protegido para floración prolongada de temporada.'],
    poda: ['Completá las podas de invierno pendientes de rosales y frutales antes de que la savia arranque y los cortes sangren.', 'Podá arbustos de floración estival sobre madera nueva (rosa china, abelia, buddleja) para estimular brotación vigorosa.', 'Realizá una poda de limpieza y despunte en gramíneas ornamentales, cortando el follaje seco casi al ras antes del rebrote.'],
    plagas: ['Pulgones en los brotes tiernos que empiezan a salir: controlá temprano con jabón potásico o favoreciendo vaquitas de San Antonio.', 'Oídio en rosales y otras plantas al reactivarse la vegetación con humedad: mantené buena ventilación y aplicá preventivos de azufre.', 'Hormigas cortadoras que reaparecen con el calor y atacan brotes nuevos: localizá el hormiguero y controlá con métodos ecológicos como cebos específicos.'],
    mantenimiento: ['Revisá, limpiá y probá todo el sistema de riego (goteros, aspersores, temporizador) antes de la demanda primaveral.', 'Terminá de tamizar el compost maduro para usarlo en almácigos, canteros y trasplantes de la temporada.', 'Prepará sustrato para almácigos y trasplantes mezclando compost, tierra y material que dé buen drenaje.'],
    flores_destacadas: [{ nombre: 'Magnolia', cientifico: 'Magnolia × soulangeana', nota: 'Abre grandes flores rosadas y blancas sobre ramas aún desnudas a fin de invierno; uno de los espectáculos más celebrados de agosto en el jardín.' }, { nombre: 'Narciso', cientifico: 'Narcissus pseudonarcissus', nota: 'Los bulbos plantados en otoño abren ahora sus trompetas amarillas, anunciando la primavera en canteros y bordes.' }, { nombre: 'Prunus de flor', cientifico: 'Prunus cerasifera', nota: 'Ciruelo ornamental que se cubre de flores rosadas o blancas a fin de invierno, uno de los primeros árboles en encender el jardín.' }],
    suggested_tasks: [{ title: 'Almácigo de tomate, pimiento y berenjena', category: 'almacigo' }, { title: 'Sembrar rúcula y rabanito', category: 'huerta' }, { title: 'Fertilización de arranque en perennes', category: 'jardin' }, { title: 'Probar el sistema de riego', category: 'mantenimiento' }, { title: 'Tamizar compost maduro', category: 'mantenimiento' }],
  },
  9: {
    estacion: 'Primavera',
    destacado: 'Septiembre despierta el jardín: es el mes de arrancar los almácigos de verano y despuntar antes de que todo se dispare.',
    jardin: ['Reanudá el riego regular a medida que sube la temperatura, siempre a la mañana temprano para evitar hongos.', 'Aplicá la primera fertilización de la temporada con un abono equilibrado o compost bien maduro en canteros y macetas.', 'Dividí y trasplantá matas de herbáceas perennes que crecieron mucho: agapantos, hemerocallis, margaritas y gramíneas ornamentales.', 'Retirá flores marchitas de las bulbosas de floración primaveral (narcisos, freesias) plantadas en otoño, pero dejá el follaje verde hasta que amarillee para recargar el bulbo.', 'Sacá el acolchado viejo apelmazado, aflojá la tierra de los canteros y renová el mantillo de superficie.', 'Plantá arbustos y perennes en pan de tierra o maceta; la ventana de raíz desnuda ya se está cerrando, así que priorizá ejemplares con cepellón antes del calor.'],
    huerta: ['Cosechá las últimas hojas de invierno: espinaca, acelga, rúcula y lechugas que empiezan a espigar.', 'Sembrá directo rabanito, zanahoria, remolacha, perejil y lechuga de estación aprovechando el suelo templado.', 'Prepará los canteros incorporando compost y estiércol bien descompuesto antes de la temporada cálida.', 'Empezá a endurecer los almácigos de invierno llevándolos afuera unas horas para aclimatarlos antes del trasplante.', 'Plantá papa temprana y cebolla de plantín si todavía no lo hiciste; el ajo ya quedó para el otoño-invierno, no se planta ahora.'],
    almacigos: ['Tomate (Solanum lycopersicum) en almácigo protegido, el clásico de fin de invierno.', 'Pimiento y ají (Capsicum annuum), que necesitan arranque temprano por su germinación lenta.', 'Albahaca (Ocimum basilicum) en bandeja con calor, para trasplantar cuando pasen los fríos.', 'Copete o tagetes (Tagetes erecta) y zinnia (Zinnia elegans) para color de verano.'],
    poda: ['Terminá la poda de rosales de fin de invierno si todavía no brotaron fuerte: dejá 3 a 5 varas sanas y limpiá el centro.', 'Podá arbustos de floración estival (hibisco, lantana, abelia) para estimular brotación nueva.', 'No podes todavía los arbustos de floración primaveral (azalea, camelia, forsitia): esperá a que terminen de florecer.'],
    plagas: ['Pulgones en brotes tiernos y pimpollos: controlá con jabón potásico o favoreciendo mariquitas y crisopas.', 'Babosas y caracoles atacando almácigos y brotes: usá trampas de cerveza o barreras de ceniza/cáscara de huevo.', 'Oídio en rosales y arvejas con la humedad primaveral: mejorá la ventilación y aplicá leche diluida o bicarbonato.'],
    mantenimiento: ['Limpiá, afilá y desinfectá las herramientas de poda antes de la temporada fuerte.', 'Volteá y humedecé la pila de compost para reactivar la descomposición con el calor.', 'Revisá y purgá el sistema de riego por goteo: destapá goteros y controlá pérdidas antes de depender de él.'],
    flores_destacadas: [{ nombre: 'Freesia', cientifico: 'Freesia refracta', nota: 'Bulbosa plantada en otoño que ahora explota en flores muy perfumadas, en amarillos, blancos y violáceos; ideal para cortar.' }, { nombre: 'Azalea', cientifico: 'Rhododendron simsii', nota: 'Arbusto de media sombra en plena floración, cubierto de flores rosadas, rojas o blancas; reina de los jardines de suelo ácido.' }, { nombre: 'Ranúnculo', cientifico: 'Ranunculus asiaticus', nota: 'Flores densas como pompones en tonos vibrantes; espectacular en cantero y como flor de corte de temporada corta.' }],
    suggested_tasks: [{ title: 'Sembrar tomate en almácigo', category: 'almacigo' }, { title: 'Primera fertilización de canteros', category: 'jardin' }, { title: 'Dividir matas de agapanto', category: 'jardin' }, { title: 'Poner trampas para babosas', category: 'huerta' }, { title: 'Afilar tijeras de poda', category: 'mantenimiento' }],
  },
  10: {
    estacion: 'Primavera',
    destacado: 'Octubre es el pico de la primavera: los rosales largan su primera floración y el jardín pide riego, tutorado y ojo con las plagas.',
    jardin: ['Ajustá el riego al ritmo del crecimiento: profundo y espaciado es mejor que superficial y diario para forzar raíces.', 'Fertilizá los rosales al iniciar la floración y repetí cada 3 o 4 semanas con un abono rico en potasio.', 'Retirá sistemáticamente las flores marchitas (deadheading) de rosas, petunias y anuales para prolongar la floración.', 'Tutorá y encañá las trepadoras y herbáceas altas (delfinios, cosmos, dalias) antes de que el viento las voltee.', 'Trasplantá al cantero definitivo los plantines de anuales de verano ya endurecidos.', 'Renová el acolchado orgánico en canteros y macetas para conservar humedad de cara al calor.'],
    huerta: ['Trasplantá al cantero los plantines de tomate, pimiento y berenjena cuando pasó todo riesgo de frío.', 'Sembrá directo zapallo, zapallito, choclo, chaucha y albahaca con el suelo ya cálido.', 'Armá los tutores y espalderas para tomate y las trepadoras antes de que crezcan.', 'Escaloná siembras de lechuga, rúcula y rabanito en media sombra para que no espiguen con el calor.', 'Aporcá las papas y mantené el suelo cubierto y con humedad pareja.'],
    almacigos: ['Berenjena (Solanum melongena) y más tomate para escalonar la cosecha.', 'Zinnia (Zinnia elegans) y girasol (Helianthus annuus) para color de pleno verano.', 'Salvia y celosía (Celosia argentea) como anuales ornamentales de temporada cálida.', 'Albahaca (Ocimum basilicum) para reponer, y cosmos (Cosmos bipinnatus) para cantero.'],
    poda: ['Podá los arbustos de floración primaveral apenas terminan (azalea, camelia, forsitia, corona de novia).', 'Pinzá las puntas de crisantemos, dalias y coleos para lograr plantas más compactas y ramificadas.', 'Retirá varas secas o mal orientadas de arbustos y trepadoras para ordenar el crecimiento nuevo.'],
    plagas: ['Pulgones y trips concentrados en pimpollos: jabón potásico, aceite de neem y control biológico con mariquitas.', 'Oídio y mancha negra en rosales: sacá hojas afectadas, ventilá y aplicá caldos con bicarbonato o cola de caballo.', 'Cochinilla en cítricos y arbustos: cepillá con alcohol o aplicá aceite mineral emulsionado.'],
    mantenimiento: ['Programá los tiempos del riego automático para el aumento de temperatura y días más largos.', 'Incorporá restos verdes y secos al compost manteniendo la proporción para que no se compacte ni apeste.', 'Revisá y repintá o tratá con protector la madera de canteros elevados, pérgolas y tutores.'],
    flores_destacadas: [{ nombre: 'Rosa', cientifico: 'Rosa × hybrida', nota: 'Primera gran floración del año: los rosales estallan en color y perfume; el momento clave para disfrutar y fertilizar.' }, { nombre: 'Glicina', cientifico: 'Wisteria sinensis', nota: 'Trepadora vigorosa que cae en racimos lilas perfumados sobre pérgolas y muros; una postal de la primavera porteña.' }, { nombre: 'Amapola de California', cientifico: 'Eschscholzia californica', nota: 'Anual rústica de flores naranjas y doradas que ama el sol pleno; ideal para bordes secos y jardines de bajo mantenimiento.' }],
    suggested_tasks: [{ title: 'Trasplantar tomates al cantero', category: 'huerta' }, { title: 'Sacar flores marchitas de rosales', category: 'jardin' }, { title: 'Armar tutores para trepadoras', category: 'huerta' }, { title: 'Renovar el acolchado', category: 'mantenimiento' }, { title: 'Sembrar zinnias en almácigo', category: 'almacigo' }],
  },
  11: {
    estacion: 'Primavera',
    destacado: 'Noviembre pinta la ciudad de violeta con los jacarandás y anticipa el verano: hay que reforzar riego, acolchado y control de arañuela.',
    jardin: ['Aumentá la frecuencia de riego con la llegada del calor, priorizando la mañana temprano o el atardecer.', 'Seguí con el deadheading de rosas, salvias y anuales para sostener la floración hasta el verano.', 'Reforzá el acolchado orgánico en todo el jardín para conservar humedad y frenar malezas antes de diciembre.', 'Fertilizá macetas y jardineras con abono líquido cada 15 días, ya que el riego lava los nutrientes.', 'Estaquá dalias, delfinios y otras herbáceas altas que se estiran rápido con el sol.', 'Plantá y acomodá anuales de verano (petunias, portulaca, copetes) en los huecos de los canteros.'],
    huerta: ['Cosechá arvejas, habas, lechugas y las primeras aromáticas de temporada.', 'Sembrá directo chaucha, choclo, zapallo, pepino y albahaca en plena tierra caliente.', 'Tutorá y desbrotá los tomates retirando los brotes axilares (chupones) para dirigir la energía a los frutos.', 'Mantené el suelo acolchado y con riego parejo para evitar el estrés hídrico y la partidura de frutos.', 'Instalá mallas o media sombra sobre las hojas tiernas para que no espiguen con el calor.'],
    almacigos: ['Puerro (Allium porrum) y apio (Apium graveolens) para cosecha de otoño.', 'Albahaca (Ocimum basilicum) de reposición para cortar todo el verano.', 'Cosmos (Cosmos bipinnatus) y tagetes (Tagetes patula) para prolongar el color estival.', 'Girasol (Helianthus annuus) escalonado para floraciones sucesivas.'],
    poda: ['Podá en verde los setos y arbustos formales (ligustro, boj) para mantener la forma con el rebrote activo.', 'Pinzá una vez más crisantemos y dalias para que lleguen compactos y florezcan en otoño.', 'Retirá los tallos florales agotados de bulbosas y perennes de primavera ya pasadas.'],
    plagas: ['Arañuela roja (Tetranychus urticae) que aparece con el calor y la sequedad: subí la humedad y aplicá aceite de neem.', 'Pulgones y mosca blanca en la huerta: jabón potásico, trampas cromáticas amarillas y fauna benéfica.', 'Oídio en zapallos, rosas y aromáticas: ventilá, evitá mojar el follaje y aplicá bicarbonato o leche diluida.'],
    mantenimiento: ['Verificá que el sistema de riego cubra toda la superficie antes de las semanas de calor fuerte.', 'Sumá material seco (hojas, poda triturada) al compost para equilibrar el exceso de verde primaveral.', 'Juntá y almacená semillas de las especies que ya cerraron su ciclo para la próxima temporada.'],
    flores_destacadas: [{ nombre: 'Jacarandá', cientifico: 'Jacaranda mimosifolia', nota: 'El árbol emblema de noviembre: se cubre por completo de flores azul-violáceas que alfombran las veredas; espectáculo urbano imperdible.' }, { nombre: 'Lavanda', cientifico: 'Lavandula dentata', nota: 'Arbusto aromático que empieza sus espigas violetas; atrae abejas y polinizadores y resiste muy bien el sol y la sequía.' }, { nombre: 'Santa Rita', cientifico: 'Bougainvillea glabra', nota: 'Trepadora rústica que se enciende en brácteas fucsias, violetas o naranjas con el calor; cubre muros y pérgolas a pleno sol y aguanta muy bien la sequía.' }],
    suggested_tasks: [{ title: 'Desbrotar chupones de tomate', category: 'huerta' }, { title: 'Reforzar el acolchado del jardín', category: 'mantenimiento' }, { title: 'Aplicar neem contra arañuela', category: 'jardin' }, { title: 'Sembrar albahaca de reposición', category: 'almacigo' }, { title: 'Fertilizar macetas con abono líquido', category: 'jardin' }],
  },
  12: {
    estacion: 'Verano',
    destacado: 'El jardín entra en plena floración estival: el riego profundo y constante manda sobre todas las tareas.',
    jardin: ['Regar temprano a la mañana o al atardecer, en profundidad y menos seguido, para forzar raíces hacia abajo antes de los calores fuertes', 'Sacar flores marchitas (deadheading) de rosas, salvias, cosmos y petunias para prolongar la floración', 'Fertilizar las plantas en floración con un fertilizante rico en potasio cada 15 días; frenar el nitrógeno para no forzar follaje blando', 'Dividir y trasplantar matas de agapanto, lirio de un día (Hemerocallis) y clivias apenas terminan de florecer', 'Tutorar dalias y gladiolos que empiezan a levantar cabeza, y renovar el mulch en los canteros para conservar humedad', 'Pinzar los brotes de crisantemos y asteres para que ramifiquen y florezcan compactos en otoño'],
    huerta: ['Cosechar de continuo lechuga, acelga, rúcula y las primeras chauchas para estimular nueva producción', 'Tutorar y desbrotar tomates: sacar los chupones de las axilas una vez por semana para aire y sol', 'Sembrar directo zanahoria, remolacha, chaucha y albahaca aprovechando el suelo caliente', 'Aporcar papas y regar de forma pareja para evitar el rajado de tomates y la pudrición apical', 'Colocar mulch de paja seca al pie de tomates, pimientos y zapallos para amortiguar el golpe de calor'],
    almacigos: ['Puerro (Allium porrum) para trasplantar en otoño', 'Repollo y coliflor de otoño (Brassica oleracea)', 'Pensamiento y viola (Viola x wittrockiana) para color de otoño-invierno', 'Albahaca (Ocimum basilicum) de reposición para siembra escalonada'],
    poda: ['Poda de limpieza en rosas: retirar flores pasadas cortando sobre una hoja de cinco foliolos, sin poda estructural', 'Despuntar setos de ligustro y teucrium ahora que están en crecimiento activo', 'Sacar varas florales agotadas de perennes y aromáticas para ordenar la mata'],
    plagas: ['Pulgones en brotes tiernos de rosas y hortalizas: controlar con jabón potásico o soltando vaquitas de San Antonio', 'Arañuela roja favorecida por el calor seco: aumentar humedad ambiente y pulverizar con agua el envés de las hojas', 'Oidio y mildiu en zapallos, rosas y vid: mejorar ventilación, evitar mojar el follaje y aplicar caldo bordelés preventivo'],
    mantenimiento: ['Revisar y limpiar goteros y aspersores del riego, y programar el timer para las horas frescas', 'Voltear la compostera y humedecerla; equilibrar con material seco (hojas, cartón) el exceso de restos verdes de verano', 'Afilar y limpiar tijeras de podar con alcohol entre planta y planta para no propagar enfermedades'],
    flores_destacadas: [{ nombre: 'Agapanto', cientifico: 'Agapanthus africanus', nota: 'Reina del verano rioplatense: sus esferas azul cielo o blancas iluminan borduras y medias sombras, y resiste sequía una vez establecido.' }, { nombre: 'Jacarandá', cientifico: 'Jacaranda mimosifolia', nota: 'Cierra su espectacular floración violeta que tiñe las calles porteñas; ideal para destacar como árbol de sombra ornamental.' }, { nombre: 'Lantana', cientifico: 'Lantana camara', nota: 'Rústica y a prueba de calor, florece sin parar en tonos que viran de amarillo a naranja y rosa, imán de mariposas.' }],
    suggested_tasks: [{ title: 'Regar en profundidad al atardecer', category: 'jardin' }, { title: 'Sacar flores marchitas de rosas y salvias', category: 'jardin' }, { title: 'Desbrotar chupones de tomate', category: 'huerta' }, { title: 'Sembrar almácigo de pensamiento y viola', category: 'almacigo' }, { title: 'Renovar mulch en los canteros', category: 'mantenimiento' }],
  },
}

export type RegionAdj = { estacion: string; notas: string[] }
export type Region = { key: string; region: string; adjustments: RegionAdj[] }

export const REGIONS: Region[] = [
  { key: 'pampa', region: 'Pampa / Buenos Aires', adjustments: [] },
  {
    key: 'patagonia',
    region: 'Patagonia / Andino',
    adjustments: [
      { estacion: 'Verano', notas: ['La temporada de crecimiento es corta e intensa: concentrá las tareas de plantación y trasplante en diciembre-enero, apenas pasado el riesgo de helada tardía, para aprovechar los días largos.', 'Regá temprano a la mañana o al atardecer y de forma profunda pero espaciada: el viento reseca mucho el suelo y evapora el riego del mediodía. Priorizá riego por goteo antes que aspersión.', 'Reforzá el mulch (corteza, chips, pinocha) para conservar humedad y moderar la amplitud térmica día/noche, que acá es más marcada que en la Pampa.', 'Instalá o mantené cortinas rompevientos (álamos, sauces, o malla) antes del pico de viento de verano; sin reparo, la floración y el cuaje se arruinan.'] },
      { estacion: 'Otoño', notas: ['Adelantá el cierre de temporada respecto de Buenos Aires: las heladas tempranas pueden llegar ya en marzo-abril, así que terminá cosechas y trasplantes antes.', 'Suspendé la fertilización nitrogenada temprano (fines de verano) para que la planta endurezca los tejidos y no la agarre la helada con brotes tiernos.', 'Es el mejor momento para plantar especies leñosas rústicas y bulbosas de raíz desnuda, para que enraícen antes del frío; protegé el cuello con mulch grueso.', 'Recogé y protegé plantas en maceta o llevalas a reparo: las macetas se congelan de lado a lado mucho más rápido que el suelo.'] },
      { estacion: 'Invierno', notas: ['Elegí especies rústicas y de reposo invernal marcado (coníferas, rosales resistentes, notros, lavandas, arbustos de origen andino/patagónico) en vez de las semitropicales que andan bien en la Pampa.', 'Protegé del frío y la desecación por viento: manta térmica (agrotextil), túneles bajos o reparo con rompevientos para lo más sensible. El daño invernal suele ser por viento seco, no solo por frío.', 'Reducí el riego al mínimo, pero no lo cortes del todo en zonas de poca nieve: el viento deshidrata la planta aunque esté dormida. Regá en días templados, nunca con suelo congelado.', 'Aprovechá el receso para poda de formación y limpieza de leñosas, y para reparar/reforzar las cortinas rompevientos antes de la primavera.'] },
      { estacion: 'Primavera', notas: ['No te apures con la siembra directa ni el trasplante: las heladas tardías llegan hasta noviembre en muchas zonas andinas. Arrancá almácigos bajo cubierta (invernadero, túnel, cajonera) y trasplantá recién pasada la última helada.', 'Tené a mano defensa antihelada para las noches claras y sin viento: manta térmica, riego por aspersión antihelada o cobertura nocturna de lo recién plantado.', 'Endurecé (rusticá) los plantines gradualmente antes de sacarlos al aire libre: el salto de temperatura y viento es más brusco que en la Pampa.', 'Escaloná la plantación según microclimas del lote: laderas norte y zonas reparadas del viento se pueden trabajar antes que las bajas donde se junta el aire frío (heladas de radiación).'] },
    ],
  },
  {
    key: 'noa',
    region: 'NOA (Noroeste)',
    adjustments: [
      { estacion: 'Verano', notas: ['Es la estación de lluvias (monzón sudamericano): concentrá las plantaciones a campo abierto en diciembre-enero para aprovechar la humedad natural, al revés que en la Pampa donde el verano suele ser seco.', 'Ojo con el exceso de agua y la humedad: mejorá el drenaje en canteros y evitá el riego por aspersión que favorece hongos (oídio, roya). Regá temprano a la mañana.', 'En zonas áridas de valles (La Rioja, Catamarca oeste) el calor es extremo y seco: instalá media sombra al 35-50% para plantines y sostené riego por goteo diario en las horas frescas.', 'Aprovechá especies nativas adaptadas al calor: lapacho, jacarandá, tipa, algarrobo, chañar, mistol, en lugar de las especies templadas que sufren el golpe de calor pampeano.'] },
      { estacion: 'Otoño', notas: ['Empieza la seca: cortá progresivamente el riego de las especies estivales y preparate para varios meses sin lluvia, muy distinto al otoño húmedo de Buenos Aires.', 'Aplicá una buena capa de mulch/acolchado (chip, paja) para conservar la humedad del suelo de cara al invierno seco.', 'Es buen momento para trasplantes y plantación de árboles en zonas serranas templadas (Tucumán, Salta capital), ya que el suelo aún conserva calor y humedad residual.', 'Sembrá cultivos de estación fresca y florales de otoño-invierno antes de que bajen las temperaturas en las zonas altas.'] },
      { estacion: 'Invierno', notas: ['Inviernos secos y suaves en los valles bajos: se puede seguir trabajando el jardín todo el invierno, adelantando podas y plantaciones respecto del calendario pampeano.', 'Cuidado con las heladas en zonas altas y de puna/prepuna (Humahuaca, valles catamarqueños de altura): protegé especies sensibles con manta antihelada o llevalas a resguardo; las heladas son más intensas por altitud aunque el día sea templado.', 'Como no llueve, mantené un riego de sostén cada 10-15 días en especies perennes y recién plantadas, algo innecesario en el invierno húmedo de la Pampa.', 'Aprovechá los días templados de invierno para dividir matas, podar frutales de carozo y preparar la tierra para la primavera.'] },
      { estacion: 'Primavera', notas: ['El período crítico es la primavera seca y ventosa antes de las lluvias: reforzá el riego, es la etapa de mayor estrés hídrico del año en el NOA.', 'Adelantá la plantación de especies estivales para que estén establecidas cuando lleguen las lluvias de fin de primavera/verano.', 'Aprovechá la floración temprana de nativas (lapacho rosado, ceibo, ceibillo) para el diseño paisajístico; florecen antes que en el sur.', 'Protegé los brotes nuevos de los vientos secos y del sol intenso con reparos o media sombra hasta que se afiancen.'] },
    ],
  },
  {
    key: 'litoral',
    region: 'Litoral / NEA (Corrientes, Misiones, Chaco, Formosa, norte de Entre Ríos y Santa Fe)',
    adjustments: [
      { estacion: 'Verano', notas: ['El estrés no es tanto por sequía como en la Pampa sino por golpe de calor y humedad: regá profundo pero espaciado, y evitá mojar el follaje al atardecer para no favorecer hongos.', 'Reforzá la vigilancia sanitaria: con esta humedad revientan hongos (oídio, mildiu, antracnosis) y bacteriosis. Aplicá preventivos y ventilá las plantas dando más distancia de plantación que en Buenos Aires.', 'Priorizá media sombra al mediodía para especies sensibles; en el NEA el sol de enero-febrero quema hortalizas de hoja y florales delicadas. Media sombra al 35-50% ayuda mucho.', 'Usá especies subtropicales que en la Pampa son de riesgo: podés tener plena bananera, papaya (mamón), mango joven, ananá, jengibre y cúrcuma prosperando al aire libre.'] },
      { estacion: 'Otoño', notas: ['Atrasá las tareas de cierre: el otoño litoraleño sigue cálido, así que la cosecha de verano se estira hasta bien entrado abril/mayo y no hay que apurar el descanso del cantero.', 'La ventana de bulbos de primavera (tulipán, jacinto) es floja acá: sin frío invernal marcado no floran bien. Priorizá bulbosas subtropicales (amarilis, clivia, agapanto, zephyranthes) que se dan de diez.', 'Podés seguir sembrando y trasplantando casi sin freno; la ausencia de heladas tempranas permite hortalizas de hoja y crucíferas durante todo el otoño sin protección.', 'Aprovechá la baja de temperatura y humedad para hacer los tratamientos sanitarios de fondo que en verano no conviene por el calor.'] },
      { estacion: 'Invierno', notas: ['Adelantá todo el calendario cálido: sin heladas o con heladas muy leves y esporádicas, los almácigos de tomate, pimiento y berenjena se pueden largar en pleno invierno, semanas antes que en la Pampa.', 'La poda de caducos se acorta: muchas especies casi no entran en reposo. Ojo con podar de más frutales subtropicales (cítricos, mango) que no toleran poda fuerte en frío.', 'Protegé de las heladas negras puntuales: aunque son raras, una helada tardía arruina cítricos jóvenes, bananeras y mamón. Tené a mano media sombra o manta para las 3-4 noches críticas del año.', 'Es la mejor época para plantar cítricos, que en el Litoral son el cultivo estrella (naranja, mandarina, pomelo, limón) y toleran perfecto el invierno suave.'] },
      { estacion: 'Primavera', notas: ['Adelantá la plantación de verano: el trasplante de tomate, pimiento y berenjena al cantero definitivo se hace en septiembre, casi un mes antes que en Buenos Aires, porque no hay riesgo de helada tardía.', 'Arrancá temprano con el control preventivo de hongos e insectos: la primavera húmeda y cálida dispara pulgones, mosca blanca, arañuela y enfermedades foliares antes que en la Pampa.', 'Reforzá el mulch y el riego desde ya: el verano subtropical pega fuerte y temprano, así que preparar el cantero para el calor no puede esperar a noviembre.', 'Sembrá directo especies de ciclo largo y calor (choclo, zapallo, batata, mandioca) apenas pasa el frío corto; tenés una temporada de crecimiento más larga que aprovechar.'] },
    ],
  },
  {
    key: 'cuyo',
    region: 'Cuyo',
    adjustments: [
      { estacion: 'Verano', notas: ['Regar de noche o al amanecer para bajar la evaporación; en la Pampa se puede regar de día sin tanta pérdida, acá no. Aprovechar el turno de acequia y acumular agua en el suelo con riegos profundos y espaciados en vez de riegos livianos y frecuentes.', 'Aplicar mulch grueso (paja, corteza, ripio en zonas de cactáceas) sobre todo cantero: con humedad ambiente baja y viento seco (zonda), el suelo se reseca mucho más rápido que en Buenos Aires.', 'Ubicar las especies sensibles con media sombra en las horas de la tarde; la radiación y la amplitud térmica castigan más que en la Pampa. Priorizar especies adaptadas al árido: olivo, vid, aromáticas mediterráneas (lavanda, romero, tomillo), algarrobo, chañar.', 'Ojo con el granizo típico de tormentas de verano cuyanas: tener malla antigranizo o reparo para huerta y frutales, algo que en la Pampa no es tan crítico.'] },
      { estacion: 'Otoño', notas: ['Adelantar la preparación para heladas: en Cuyo las primeras heladas llegan antes y son más intensas que en Buenos Aires. Empezar a acollar y proteger base de plantas jóvenes desde fines de otoño.', 'Aprovechar el otoño para plantar leñosas y frutales de hoja caduca a raíz desnuda (vid, olivo, frutales de carozo): con el suelo aún tibio enraízan antes del frío fuerte.', 'Reducir progresivamente la frecuencia de riego acompañando el descenso de temperatura, pero sin cortarlo del todo: la baja humedad sigue secando el perfil aunque no haga calor.', 'Recolectar y guardar la poda/hojarasca para compost y mulch; el material orgánico escasea más que en la húmeda Pampa y conviene reciclarlo todo.'] },
      { estacion: 'Invierno', notas: ['Protección de heladas como tarea central (no marginal como en la Pampa): usar cobertores, media sombra invertida, botellas/agua como masa térmica y riego previo a la helada para atemperar. Las heladas cuyanas son severas y con amplitud térmica grande.', 'Concentrar la poda de vid, olivo y frutales de carozo en pleno reposo invernal; es la ventana ideal y más marcada que en el clima templado húmedo.', 'Regar poco pero no suspender: el aire seco deshidrata las perennes aun en invierno. Regar al mediodía en días templados para que el agua no se congele en el perfil de noche.', 'Aprovechar el descanso para limpiar y mantener acequias, compuertas y regueras antes de la temporada de riego; el manejo del agua por turno exige la infraestructura a punto.'] },
      { estacion: 'Primavera', notas: ['Atrasar las siembras y trasplantes sensibles respecto de la Pampa: esperar a que pase el riesgo de heladas tardías, que en Cuyo se extienden más y son traicioneras.', 'Coordinar con el calendario de la acequia: la disponibilidad de agua de deshielo marca el arranque real de la temporada; planificar la carga de canteros según el turno asignado.', 'Instalar o revisar riego por goteo para las nuevas plantaciones: maximiza el aprovechamiento del agua escasa y evita perder el turno de acequia por escurrimiento.', 'Aprovechar la floración temprana de especies mediterráneas y nativas del monte (jarilla, algarrobo, aromáticas) que rinden mejor acá que las de jardín húmedo pampeano; sumar cortinas rompeviento para mitigar el zonda primaveral.'] },
    ],
  },
]

export const TASK_CATEGORIES = [
  { id: 'jardin', label: 'Jardín', color: '#4C7F5B' },
  { id: 'huerta', label: 'Huerta', color: '#C4773B' },
  { id: 'almacigo', label: 'Almácigo', color: '#6B5B95' },
  { id: 'mantenimiento', label: 'Mantenimiento', color: '#2563EB' },
] as const
